apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-app-deployment
  namespace: my-app-namespace
spec:
  replicas: 3
  selector:
    matchLabels:
      app: my-app
  template:
    metadata:
      labels:
        app: my-app
    spec:
      containers:
      - name: my-app
        image: my-app
        ports:
        - containerPort: 3000
        volumeMounts:
        - name: my-app-static-volume
          mountPath: /app/static
      volumes:
      - name: my-app-static-volume
        persistentVolumeClaim:
          claimName: my-app-static-pvc
